# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('all_components', models.BooleanField(default=False)),
                ('remove_on_update', models.BooleanField(default=False, help_text=b'Remove package from index prior to adding a new version of the package.')),
                ('components', models.ManyToManyField(to='distribution.Component')),
            ],
        ),
    ]
