# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20151205_1726'),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='components',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
    ]
