# Generated by Django 1.9 on 2015-12-25 12:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reprepro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='released',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='supported_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='components',
            field=models.ManyToManyField(blank=True, to='django_reprepro.Component'),
        ),
        migrations.AlterField(
            model_name='package',
            name='all_components',
            field=models.BooleanField(default=False, help_text='If set, the package will be automatically added to all known components.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='components',
            field=models.ManyToManyField(blank=True, to='django_reprepro.Component'),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
