# Generated by Django 1.9 on 2015-12-25 18:16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reprepro', '0004_auto_20151225_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='supported_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
