# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('vendor', models.SmallIntegerField(choices=[(0, 'Debian'), (1, 'Ubuntu')])),
                ('components', models.ManyToManyField(to='apt_repositories.Component')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('all_components', models.BooleanField(default=False)),
                ('remove_on_update', models.BooleanField(default=False, help_text='Remove package from index prior to adding a new version of the package.')),
                ('components', models.ManyToManyField(to='apt_repositories.Component')),
            ],
        ),
    ]
