# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
